dist: bionic
language: java
jdk: openjdk8
     
addons:
   sonarcloud:
      organization: "predictabowl"
      token: $SONAR_TOKEN

cache:
   directories:
      - $HOME/.m2
      - $HOME/.sonar/cache 

services:
   - xvfb
  
install: true

script:
   #- ./build
   
   - mvn -f demo-spring-testing/pom.xml clean verify -Pjacoco coveralls:report sonar:sonar -Dsonar.projectKey=Predictabowl_SpringBoot-Tutorial
   #- mvn -f demo-spring-testing/pom.xml verify -Pe2e-tests