language: java

jdk: openjdk8
     
install: true

cache:
   directories:
      - $HOME/.m2
      - $HOME/.sonar/cache 

script:
   - mvn -f demo-spring-testing/pom.xml clean verify -Pjacoco coveralls:report