dist: bionic
language: java
jdk: openjdk8
     
install: true

addons:
   sonarcloud:
      organization: "predictabowl"
      token: $SONAR_TOKEN

cache:
   directories:
      - $HOME/.m2
      - $HOME/.sonar/cache 

script:
   - mvn -f demo-spring-testing/pom.xml clean verify sonar:sonar